name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make libs
      run: make libs
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make tests
    - name: Test C
      run: ./test_c
    - name: Test C++
      run: ./test_cpp
